server:
  port: 8760
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: service
          uri: lb://service1
          predicates:
            - Path=/service1/**
        - id: eureka
          uri: lb://registry
          predicates:
              - Path=/eureka/**
          filters:
            - StripPrefix=1

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    refresh:
      enable: true