spring:
  application:
    name: service1
server:
  port: 8762
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    refresh:
      enable: true
